### ISSUE TITLE
Tiles directory could not be created

### ISSUE THREAD

**Issue by Unforgiven-wanda** [mellet/expo-offline-mapview#1]
Hello,
The process of downloading the tiles seems to fail with the following error: 
`Possible unhandled promise rejection: Directory file:///data/user/0/host.exp.exponent/files/ExperienceData/%2540unforgiven%252FigniteExpo/tiles/10/58 could not be created`

At first I thought this might have to do with running in dev mode. However, the issue remains in prod and released apk as well

This is my first time using Expo so I'd appreciate any pointers.
Thank you.

**Comment by mellet** [comment]
You using it as following?
```
FileSystem.makeDirectoryAsync(folder, {intermediates: true,}
```

If you don't have the intermediates set to true it might be why it's failing for you 💯

**Comment by Unforgiven-wanda** [comment]
I am using this untouched repo.
I have tried it on both device and emulator as well, to the same effect.

**Comment by mellet** [comment]
I'l take a look at it if it's breaking for me.
